name: Build

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Publish
        run: ./gradlew publish --stacktrace
        env:
          ORG_GRADLE_PROJECT_nexus_user: ${{ secrets.NEXUS_USER }}
          ORG_GRADLE_PROJECT_nexus_password: ${{ secrets.NEXUS_PASSWORD }}
